# Generated by Django 5.0.1 on 2024-01-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_task_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created',
        ),
        migrations.AddField(
            model_name='todo',
            name='finish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
